export const MARKET_OVERVIEW_URL = "/overview"
export const MARKET_LISTING_URL = "/coins/list"
export const COIN_DETAIL_URL = "/coin/single"
export const COIN_DETAIL_HISTORY_URL = "/coin/single/history"
export const FEAR_AND_GREED_INDEX_URL = "/fng/"
export const NEWS_URL = "/posts/"
